name: MarketPlace
version: '1.0'
main: gg.kite.core.Main
api-version: 1.21
authors: [ KiteGG ]
website: https://ks.akii.pro
softdepend: [Vault]

commands:
  marketplace:
    description: Opens the marketplace GUI or performs marketplace-related actions
    usage: /<command> [gui|sell|blackmarket|transactions|list|admin]
    permission: marketplace.view
    permission-message: You don't have permission to use this command!

permissions:
  marketplace.view:
    description: Allows players to view the marketplace
    default: true
  marketplace.admin:
    description: Allows players to use admin commands for the marketplace
    default: op
  marketplace.sell:
    description: Allows players to sell items on the marketplace
    default: true